### GET request to example server
GET http://localhost:8080/todo

### POST request to add a TODO
POST http://localhost:8080/todo

{
"item": "go for a walk"
}

### GET request to search a TODO
GET http://localhost:8080/search?q=Shop

